{"uuid": "0fe06609-8489-47e2-8242-3ee45a966120", "children": ["37b14a32-ea0d-4cd9-b53a-5943db27a69d"], "befores": [{"name": "log_on_failure", "status": "passed", "start": 1645680325047, "stop": 1645680325047}], "afters": [{"name": "log_on_failure::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'rep_call'\n", "trace": "  File \"C:\\Users\\Cassandra\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\allure_commons\\_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"C:\\Users\\Cassandra\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 941, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\Cassandra\\PycharmProjects\\UnoDosTres\\test\\test_Undostres.py\", line 23, in log_on_failure\n    if item.rep_call.failed:\n"}, "start": 1645680384128, "stop": 1645680384193}], "start": 1645680325047, "stop": 1645680384193}